version: "3.8"

services:
  app:
    build:
      context: .
      args:
        - DEV=true  # Pass the DEV argument during build
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 2>&1"
